"""message

Revision ID: 0df23e2e9d52
Revises: 38b0308be061
Create Date: 2025-02-05 22:11:05.794996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df23e2e9d52'
down_revision = '38b0308be061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
